print(bool(1))
print(bool(836))
print(bool(2.14))
print(bool(-16))
print(bool("hello"))
print(bool(" "))
print(5>3)
print(2<10)
print(4==4)
print(True)
#______________________
print(bool(0))
print(bool(0.0))
print(bool([]))
print(bool(()))
print(bool({}))
print(bool(""))
print(bool(None))
#______________________
print(1 or 0)
print(1 or 1)
print(0 or 0)
print(False or True)
print(1 and 1)
print(1 and 0)
print(0 and 0)
print(False and True)
print(not 1)
print(not 0)
print(not False)
#______________________

